name: Snap Hutao Alpha
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '.gitattributes'
      - '.github/**'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'

jobs:
  publish-alpha:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0

      - name: Cake
        id: cake
        shell: pwsh
        run: dotnet tool restore && dotnet cake
        env:
          VERSION_API_TOKEN: ${{ secrets.VERSION_API_TOKEN }}

      - name: Sign Msix
        shell: pwsh
        run: |
          [System.Convert]::FromBase64String("${{ secrets.CERTIFICATE }}") | Set-Content -AsByteStream temp.pfx
          signtool.exe sign /debug /v /a /fd SHA256 /f temp.pfx /p ${{ secrets.PW }} ${{ github.workspace }}\src\output\Snap.Hutao.Alpha-${{ steps.cake.outputs.version }}.msix

      - name: Upload signed msix
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: Snap.Hutao.Alpha-${{ steps.cake.outputs.version }}
          path: ${{ github.workspace }}/src/output/Snap.Hutao.Alpha-${{ steps.cake.outputs.version }}.msix
