name: PublishDistribution

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      # Purge Patch System Cache
      - name: Purge Patch
        env:
          PURGE_URL: ${{ secrets.PURGE_URL }}
        run: |
          curl -X PATCH $PURGE_URL
      - uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: overwrite
          repo: qhy040404/CN-Overwriter
          ref: main
          token: "${{ secrets.RUNNER_CHECK_TOKEN }}"
      - uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: Build
          repo: DGP-Studio/hutao-installer
          ref: main
          token: "${{ secrets.RUNNER_CHECK_TOKEN }}"
          inputs: '{ "only-offline": true }'
