name: PublishDistribution

on:
  release:
    types: [released]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      # Purge Patch System Cache
      - name: Purge Patch
        env:
          PURGE_URL: ${{ secrets.PURGE_URL }}
        run: |
          curl -X PATCH $PURGE_URL
      
      - name: Sync development appxmanifest
        env:
          VERSION: ${{ github.ref }}
        shell: pwsh
        run: |
          $ver = '  Version="'+$Env:VERSION+'.0"'
          $content = (Get-Content src/Snap.Hutao/Snap.Hutao/Package.development.appxmanifest -Encoding UTF8) -replace '  Version="([0-9\\.]+)"', $ver
